# <a href = "../README.md" target="_blank">스프링 DB 1편 - 데이터 접근 핵심 원리</a>
## Chapter 05. 자바 예외 이해
### 5.3 체크 예외 기본 이해
1) Exception을 상속받은 예외는 체크예외가 된다.
2) 체크 예외를 잡아서 처리하거나 떠넘기지 않으면 컴파일 오류 발생
3) 체크예외를 잡아서 처리하기
4) 체크 예외를 떠넘기기
5) `catch`는 해당 타입과 그 하위 타입을 모두 잡을 수 있다.
6) `throws`는 해당 타입과 그 하위 타입을 모두 떠넘길 수 있다.
7) 체크 예외의 장단점

---

# 5.3 체크 예외 기본 이해

---

## 1) Exception을 상속받은 예외는 체크예외가 된다.

```java
    static class MyCheckedException extends Exception {

        public MyCheckedException(String message) {
            super(message);
        }
    }
```
- `Exception` 및 이를 상속받은 하위 예외들은 체크 예외가 된다.
  - 위의 코드에서 `MyCheckedException` 는 Exception 을 상속받았으므로 체크 예외이다.
- 단, `Exception`의 하위클래스인 `RuntimeException` 을 상속받으면 언체크 예외가 된다.
- 예외가 제공하는 여러가지 기본 기능이 있는데, 그 중에 오류 메시지를 보관하는 기능도 있다.
  - 예제에서 보는 것 처럼 생성자를 통해서 해당 기능을 그대로 사용하면 편리하다.

---

## 2) 체크 예외를 잡아서 처리하거나 떠넘기지 않으면 컴파일 오류 발생
```java
    static class Repository {
        public void call() {
            throw new MyCheckedException("ex"); // 체크 예외를 처리하지 않았으므로 컴파일 오류 발생
        }
    }
```
- Repository의 call 메서드에서, 체크예외를 발생시키는 `throw`문을 작성했다.
- 체크 예외를 잡아 처리(`try-catch`)하지도 않았고, 밖으로 떠넘기지도(`throws`) 않으면 여기서 컴파일 오류가 발생한다.
  - `Unhandled exception: com.ttasjwi.jdbc.exception.basic.CheckedTest.MyCheckedException`
- 체크 예외를 잡아서 처리하거나, 바깥 계층으로 처리를 떠넘겨야 컴파일 오류가 발생하지 않는다.
  - 실습을 위해 여기서는 MyCheckedException을 밖으로 throws 하도록 한다.

---

## 3) 체크예외를 잡아서 처리하기

### 3.1 callCatch : 예외를 잡아서 처리
```java
    public void callCatch() {
        try {
            repository.call();
        } catch (MyCheckedException e) {
            // 예외 처리 로직
            log.error("예외 처리, message = {}", e.getMessage(), e);
        }
    }
```
- 체크 예외를 잡아서 처리하려면 `try-catch` 를 사용해서 예외를 잡으면 된다.
- 여기서는 MyCheckedException 예외를 잡아서 처리한다.


### 3.2 테스트 코드 작성 및 분석
```java
    @Test
    @DisplayName("예외 catch!")
    public void checked_catch() {
        service.callCatch();
    }
```
- `service.callCatch()` 에서 예외를 처리했기 때문에 테스트 메서드까지 예외가 올라오지 않는다.
- 실행 순서 분석
  1. `test` → `service.callCatch()` → `repository.call()`(예외 발생, 던짐)
  2. `test` ← `service.callCatch()`(예외 처리) ← `repository.call()`
  3. `test`(정상 흐름) ← `service.callCatch()` ← `repository.call()`


### 3.3 예외 로그 확인

실제로 실행해보면 로그가 나오는데, catch문에서 작성한 코드에 해당한다. `Repository.call()` 에서 `MyUncheckedException` 예외가 발생하고, 그 예외를 `Service.callCatch()` 에서 잡는 것을 확인할 수 있다.

```java
log.info("예외 처리, message={}", e.getMessage(), e);
```
```shell
[main] ERROR ttasjwi.jdbc.exception.basic.CheckedTest - 예외 처리, message = ex
ttasjwi.jdbc.exception.basic.CheckedTest$MyCheckedException: ex
	at ttasjwi.jdbc.exception.basic.CheckedTest$Repository.call(CheckedTest.java:75)
	at ttasjwi.jdbc.exception.basic.CheckedTest$Service.callCatch(CheckedTest.java:57)
	at ttasjwi.jdbc.exception.basic.CheckedTest.checked_catch(CheckedTest.java:22)
```
- 실행 결과 로그를 보면 첫줄은 우리가 남긴 로그가 그대로 남는 것을 확인할 수 있다.
- 그런데 두 번째 줄 부터 예외에 대한 스택 트레이스가 추가로 출력된다. 
- 이 부분은 로그를 남길 때 로그의 마지막 인수에 예외 객체를 전달해주면 로그가 해당 예외의 스택 트레이스를 추가로 출력해주는 것이다.
  - `log.info("예외 처리, message={}", e.getMessage(), e);` ← 여기서 마지막에 있는 e 부분이다.

---

## 4) 체크 예외를 떠넘기기

### 4.1 callThrow : 예외를 바깥으로 떠넘김
```java
    public void callThrow() throws MyCheckedException {
        repository.call();
    }
```
- 체크 예외를 처리할 수 없을 때는 메서드의 `throws 예외` 을 사용해서 밖으로 던질 예외를 필수로 지정해주어야 한다.
- 여기서는 `MyCheckedException` 을 밖으로 던지도록 지정해주었다.

### 4.2 테스트 코드 작성 및 분석
```java
    @Test
    @DisplayName("예외 throw!")
    public void checked_throws() {
        assertThatThrownBy(() -> service.callThrow())
                .isInstanceOf(MyCheckedException.class);
    }
```
- service.callThrow() 에서 예외를 처리하지 않고, 밖으로 던졌기 때문에 예외가 테스트 메서드까지 올라온다.
- 테스트에서는 기대한 것 처럼 `MyCheckedException` 예외가 던져진 것을 성공으로 처리한다.
- 실행 순서 분석
  1. `test` → `service.callThrow()` → `repository.call()`(예외 발생, 던짐)
  2. `test` ← `service.callThrow()`(예외 던짐) ← `repository.call()`
  3. `test`(예외 도착) ← `service.callThrow()` ← `repository.call()`

---

## 5) `catch`는 해당 타입과 그 하위 타입을 모두 잡을 수 있다.
```java
    public void callCatch() {
        try {
            repository.call();
        } catch (Exception e) {
            //예외 처리 로직
        }
    }
```
- `catch` 에 `MyCheckedException` 의 상위 타입인 Exception 을 적어주어도 MyCheckedException을 잡을 수 있다.
- `catch` 에 예외를 지정하면 해당 예외와 그 하위 타입 예외를 모두 잡아준다.
- 정확하게 MyCheckedException 만 잡고 싶다면 catch 에 MyCheckedException 을 적어주어야한다.

---

## 6) `throws`는 해당 타입과 그 하위 타입을 모두 떠넘길 수 있다.
```java
public void callThrow() throws Exception {
    repository.call();
}
```
- throws 에 `MyCheckedException`의 상위 타입인 `Exception` 을 적어주어도 `MyCheckedException`을 던질 수 있다.
- throws 에 지정한 타입과 그 하위 타입 예외를 밖으로 던진다.
- 물론 정확하게 MyCheckedException 만 밖으로 던지고 싶다면 throws 에 MyCheckedException 을 적어주어야 한다.

---

## 7) 체크 예외의 장단점
체크 예외는 예외를 잡아서 처리할 수 없을 때, 예외를 밖으로 던지는 throws 예외 를 필수로 선언해야 한다.  
그렇지 않으면 컴파일 오류가 발생한다. 이것 때문에 장점과 단점이 동시에 존재한다.  

- 장점 : 개발자가 실수로 예외를 누락하지 않도록 컴파일러를 통해 문제를 잡아주는 훌륭한 안전 장치이다.
- 단점
  - 실제로는 개발자가 모든 체크 예외를 반드시 잡거나 던지도록 처리해야 하기 때문에, 너무 번거로운 일이 된다.
  - 크게 신경쓰고 싶지 않은 예외까지 모두 챙겨야 한다.
  - 의존관계에 따른 단점도 있는데 이 부분은 뒤에서 다룬다.

---
